<header id="header" class="alt style2">
      <a href="/" class="logo"><strong>BlackLit</strong> <span>Online</span></a>
			<nav>
				<a href="#menu">Menu</a>
      </nav>
</header>



<!-- Menu -->
<nav id="menu">
		<ul class="links">
			<li><a href="/novelgeneratormachine">Novel Generator Machine</a></li>
			<li><a href="/collection">Literary Data Gallery</a></li>
			<li><a href="/remarkablereceptions">Remarkable Receptions</a></li>
			<li><a href="/briefs">Multithreaded Literary Briefs</a></li>
		</ul>
		<ul class="actions stacked">
			<li><a href="#" class="button primary fit">Home</a></li>
			<li><a href="/login/" class="button fit">Log In</a></li>
		</ul>
</nav>
